language: generic

sudo: required

services:
  - docker

# 설치 하기전에 확인하기
before_install:
  - docker build -t connor/react-app -f ./frontend/Dockerfile.dev ./frontend

# test 스크립트를 실행하여 검증한다.
script:
  - docker run -e CI=true connor/react-app npm test

after_success:
  - docker build -t connor/docker-frontend ./frontend
  - docker build -t connor/docker-backend ./backend
  - docker build -t connor/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push connor/docker-frontend
  - docker push connor/docker-backend
  - docker push connor/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-fullstack-app"
  env: "DockerFullstackApp-env"
  bucket_name: elasticbeanstalk-ap-northeast-2-972153559337
  bucket_path: "docker-fullstack-app"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
